### ISSUE TITLE
Allow default HTML keywords to touch the curly braces

### ISSUE THREAD

**Issue by marquizzo** [braver/LessImproved#3]
It would be great if default HTML keywords would be highlighted without the need of adding a space before opening curly braces. For example: 
 
![htmldefaults](https://user-images.githubusercontent.com/7864858/27453272-1b88661c-5753-11e7-8831-08166124dfc4.png)

`html` and `main` are highlighted because they have a space before the curly braces, but `body` and `section` are not highligthed because they are touching the `{`. This would be very helpful for people with different formatting traditions :)

Side note: Thanks for improving on LESS highlighting after all these years!

**Comment by braver** [comment]
@marquizzo thanks, I got it! fixed  in 2.0.2.

**Comment by marquizzo** [comment]
Nice, that was fast! Took me longer to write up the issue than it took you to make the update.

**Comment by braver** [comment]
Yeah, seemed easy enough. Can't promise to always be this fast though ;)
